apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-frontend
  template:
    metadata:
      labels:
        app: currency-frontend
    spec:
      containers:
        - name: currency-frontend
          image: prabel1/currency-front:latest
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: currency-frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30173 